[tool.poetry]
name = "versionizer"
version = "0.1.2"
description = "Versionizer is a tool for automatically generating unit tests for functions that change between two commits."
authors = ["Jordan Gillard <jordan-gillard@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8"
GitPython = "^3.1.15"
astor = "^0.8.1"
pytest = "^6.2.4"
pynguin = "^0.8.0"
asciistuff = "^1.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
