
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-07T20:40:35-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "21a00fcf2492d774a389cb41d834c002468ba7ac",
 "version": "0.8.286"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
