[tool.poetry]
name = "oslodb_sqlalchemy_exceptions"
version = "0.1.0"
description = ""
authors = ["Douglas Bett <bettdalpha@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
SQLAlchemy = "^1.2.0"
debtcollector = "^1.2.0"
funcsigs = "1.0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
