on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    tags:
      - "v*"

name: Build precompose_utils

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build wheel
        run: make wheel

      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push'
        with:
          name: precompose_utils
          path: |
            dist/precompose_utils-*.whl
            dist/precompose_utils-*.tar.gz

  release:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'

    needs:
      - build

    steps:
      - uses: actions/download-artifact@v2
        with:
          path: ./artifacts

      - name: Rearrange artifacts
        run: |
          mkdir -p dist
          mv ./artifacts/*/* dist/

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

      - name: Publish package to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

      - uses: actions/checkout@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: generate-changelog
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filterByMilestone: false
          verbose: true
          onlyLastTag: true

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          body: ${{ steps.generate-changelog.outputs.changelog }}
          files: |
            dist/precompose_utils-*.tar.gz
            dist/precompose_utils-*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
