[tool.poetry]
name = "djangophysics"
version = "0.9.2"
description = "Integrate currencies and measure conversions in a Django project"
authors = ["Frederic Meurou <fm@peabytes.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1.5"
django-cors-headers = "^3.6.0"
django-cors-middleware = "^1.5.0"
django-createsuperuser = "^2020.12.3"
django-extensions = "^3.1.0"
django-filter = "^2.4.0"
django-redis = "^4.12.0"
django-sendfile = "^0.3.11"
djangorestframework = "^3.12.2"
drf-yasg = "^1.20.0"
Markdown = "^3.3.3"
lxml = "^4.6.2"
pysendfile = "^2.0.1"
gunicorn = "^20.0.4"
pytz = "^2020.5"
pycountry = "^20.7.3"
countryinfo = "^0.1.2"
timezonefinder = "^5.0.0"
iso4217 = "^1.6.20180829"
forex-python = "^1.5"
Babel = "^2.8"
Pint = "^0.15"
coverage = "^5.3.1"
pylint-venv = "^2.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
