[tool.poetry]
name = "starlette-static-resources"
version = "0.1.0"
description = ""
authors = ["david <davidventura27@gmail.com>"]

[tool.black]
line-length = 88
py36 = true

[tool.poetry.dependencies]
python = ">=3.6"
starlette = "^0.14.2"
importlib-resources = { version = "^5.1.2", python = "<3.9" }
aiofiles = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.6"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
