name: test-environment
channels:
  - conda-forge
dependencies:
  - distributed
  - toolz
  - sphinx
  - pyyaml
  - pyproj
  - coveralls
  - coverage
  - codecov
  - behave
  - mock
  - pytest
  - pytest-cov
  - pip
  - pip:
    - trollsift
    - posttroll