[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
branch = "main"
version_variable = [
    '__version__.py:__version__',
]
