[tool.poetry]
name = "vaccinegov"
version = "0.0.1"
description = "A library to interact with the U.S Government's COVID-19 Vaccine Finder tool"
authors = ["Mustafa <mustafa@ms7m.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.18.1"
arrow = "^1.1.0"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
black = "^21.5b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
