# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cloudfirewall.grpc import agent_pb2 as cloudfirewall_dot_grpc_dot_agent__pb2


class AgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/cloudfirewall.Agent/Heartbeat',
                request_serializer=cloudfirewall_dot_grpc_dot_agent__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=cloudfirewall_dot_grpc_dot_agent__pb2.ServerResponseAck.FromString,
                )
        self.SendResponse = channel.unary_unary(
                '/cloudfirewall.Agent/SendResponse',
                request_serializer=cloudfirewall_dot_grpc_dot_agent__pb2.CommandResponse.SerializeToString,
                response_deserializer=cloudfirewall_dot_grpc_dot_agent__pb2.ServerResponseAck.FromString,
                )


class AgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """send a heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendResponse(self, request, context):
        """Send response to command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=cloudfirewall_dot_grpc_dot_agent__pb2.HeartbeatRequest.FromString,
                    response_serializer=cloudfirewall_dot_grpc_dot_agent__pb2.ServerResponseAck.SerializeToString,
            ),
            'SendResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.SendResponse,
                    request_deserializer=cloudfirewall_dot_grpc_dot_agent__pb2.CommandResponse.FromString,
                    response_serializer=cloudfirewall_dot_grpc_dot_agent__pb2.ServerResponseAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloudfirewall.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Agent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudfirewall.Agent/Heartbeat',
            cloudfirewall_dot_grpc_dot_agent__pb2.HeartbeatRequest.SerializeToString,
            cloudfirewall_dot_grpc_dot_agent__pb2.ServerResponseAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudfirewall.Agent/SendResponse',
            cloudfirewall_dot_grpc_dot_agent__pb2.CommandResponse.SerializeToString,
            cloudfirewall_dot_grpc_dot_agent__pb2.ServerResponseAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
