#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['asyncstdlib']

package_data = \
{'': ['*']}

extras_require = \
{":python_version<'3.8'": ['typing_extensions'],
 'doc': ['sphinx', 'sphinxcontrib-contentui', 'sphinxcontrib-trio'],
 'test': ['pytest >=4.3.0', 'flake8', 'flake8-bugbear', 'coverage'],
 "test:implementation_name=='cpython'": ['black']}

setup(name='asyncstdlib',
      version='3.9.2',
      description='The missing async toolbox',
      author='Max Fischer',
      author_email='maxfischer2781@gmail.com',
      url='https://github.com/maxfischer2781/asyncstdlib',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
     )
