
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-26T13:11:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4df45cc2851c979c3a1402bc6f0ec96a4597998d",
 "version": "0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
