[tool.poetry]
name = "captif-db-config"
version = "0.4"
description = ""
license = "MIT"
authors = ["John Bull <john.bull@nzta.govt.nz>"]
readme = "README.md"
keywords = ["CAPTIF"]

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = "1.3.20"
sqlalchemy-utils = "^0.37.2"
mysqlclient = "^2.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
