[tool.poetry]
name = "prey"
version = "0.1.1"
description = "A tool for writing shell scripts in python."
authors = ["Sachin Raja <sachinraja2349@gmail.com>"]
readme = "README.md"
repository="https://github.com/cloudagon/prey"

[tool.poetry.scripts]
prey =  "bin.prey:main"

[tool.poetry.dependencies]
python = "^3.9"
colorama = "^0.4.4"
aiohttp = "^3.7.4"
aiohttp-requests = "^0.1.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.5b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
