
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-13T17:47:50+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1afddb23f10c835c178393f470c6f946f4ff1e2d",
 "version": "2.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
