from dagster_utils.typing import DagsterConfigDict as DagsterConfigDict
from typing import Any, Optional

class PreconfigurationLoader:
    name: str
    config_file_directory: str
    optional_keys: set[str]
    required_keys: set[str]
    def file_path(self, filename: str) -> str: ...
    def load_config(self, filename: str) -> Optional[DagsterConfigDict]: ...
    def validated_config(self, config: DagsterConfigDict) -> DagsterConfigDict: ...
    def load_files(self, filenames: list[str]) -> list[DagsterConfigDict]: ...
    def load_for_mode(self, mode: str) -> DagsterConfigDict: ...
    def __init__(self, name: Any, config_file_directory: Any, optional_keys: Any, required_keys: Any) -> None: ...
