[tool.poetry]
name = "ehelply-python-sdk"
version = "0.2.8"
description = ""
authors = ["Shawn Clake <shawn.clake@ehelply.com>"]
readme = "readme.md"
homepage = "https://ehelply.com"

[tool.poetry.dependencies]
python = "~3.8"
requests = "^2.25.1"
python-jose = "^3.2.0"
PyJWT = "^2.1.0"
passlib = "^1.7.4"
cryptography = "^3.4.7"
pyOpenSSL = "^20.0.1"
typer = "^0.3.2"
python-dateutil = "^2.8.1"
python-slugify = "^5.0.2"
wheel = "^0.36.2"
ehelply-logger = "^0.0.8"
pytest-cov = "^2.11.1"
pytest-asyncio = "^0.15.1"
isodate = "^0.6.0"
pydantic = "^1.8.2"
pdoc3 = "^0.9.2"
httpx = "^0.18.1"

[tool.poetry.scripts]
ehelply_sdk = 'ehelply_python_sdk.cli:cli_main'

[tool.poetry.dev-dependencies]
pytest = "^5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
