package: 
  name: "ts-integrationtests"
  version: "0.0.1"

source:
  path: ..

build:
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

about:
  home: "https://github.com/lsst-ts/ts_IntegrationTests"

