[tool.poetry]
name = "musamusa_fal"
version = "0.0.7"
description = "Use this package to store a filename and a line number."
authors = ["suizokukan <suizokukan@orange.fr>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.9"
musamusa-jsonclass = "^0.0.1"
rich = "^10.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
