[tool.poetry]
name = "housepaint"
version = "0.0.1"
description = "Colour all the output!"
authors = ["Nicholas Lambourne <nick@ndl.im>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = ""
repository = "https://github.com/nicklambourne/housepaint"
documentation = "https://github.com/nicklambourne/housepaint"
keywords = [
    "ANSI",
    "Color",
    "Tutorial"
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
