[tool.poetry]
name = "firrtl"
version = "0.1.1"
description = "Python Bindings for FIRRTL"
authors = ["Dan Fritchman <dan@fritch.mn>"]

[tool.poetry.dependencies]
python = "^3.8"
protobuf = "^3.17.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
