# YOLO model
yolov3:
  model_dir: aggdirect_ocr_models/
  class_names: ['ticket_number']
  anchors: '10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326'
  train_data_dir : aggdirect_ocr_training_data/yolo
  score: 0.25
  iou: 0.45
  gpu_num: 1
  model_image_height: 416
  model_image_width: 416
  batch_size: 32
  epochs: 11
  val_split: 0.3

# Classification model
classifier:
  model_dir: aggdirect_ocr_models/
  model_image_height: 180
  model_image_width: 180
  classes: ['dump', 'non-dump']
  train_data_dir : aggdirect_ocr_training_data/classifier
  batch_size: 32
  epochs: 20
  val_split: 0.2

# Tesseract digit recognition model
digits:
  model_dir: aggdirect_ocr_models/
  lang: digits_latest
  oem: 3
  psm: 8
  train_data_dir: aggdirect_ocr_training_data/digits