[tool.poetry]
name = "rundeckpy"
version = "0.2.8"
description = "Rundeck python plugins, helper functions and cli tool"
authors = ["Thiago Takayama <thiago@takayama.co.uk>"]
license = "Proprietary"
readme = "README.rst"
homepage = "https://gitlab.com/labitup/rundeck/rundeckpy/-/wikis/home"
repository = "https://gitlab.com/labitup/rundeck/rundeckpy"
documentation = "https://gitlab.com/labitup/rundeck/rundeckpy/-/wikis/home"
keywords = ["rundeck", "python", "plugin"]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
paramiko = "^2.7.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pylint = "^2.7.4"
black = "^20.8b1"
coverage = {extras = ["toml"], version = "^5.5"}
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
rundeckpy = "rundeckpy.rundeckpy:cli"
rdpy = "rundeckpy.rundeckpy:cli"

[tool.coverage.run]
omit = [".*", "*/site-packages/*"]

[tool.coverage.report]
fail_under = 80
