[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ModernRelay"
author = "Brett Buford"
author-email = "blbuford@gmail.com"
home-page = "https://github.com/blbuford/ModernRelay"
requires = [
    "aiofiles",
    "aiohttp",
    "aiosmtpd",
    "APScheduler",
    "argon2-cffi",
    "confuse",
    "msgraph-async",
]
requires-python = ">=3.6"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Communications :: Email",
]
description-file = "README.rst"

[tool.flit.metadata.requires-extra]
test = [
    "asynctest",
    "coverage",
    "flake8",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-sugar",
    "tox"
]
dev = [
    "check-manifest",
    "python-dotenv",
]
doc = [
    "sphinx",
    "sphinx_RTD_theme"
]