[tool.poetry]
name = "nautobot-chatops"
version = "v1.3.0"
description = "A plugin providing chatbot capabilities for Nautobot"
authors = ["Network to Code, LLC <opensource@networktocode.com>"]
readme = "README.md"
homepage = "https://github.com/nautobot/nautobot-plugin-chatops"
repository = "https://github.com/nautobot/nautobot-plugin-chatops"
keywords = ["nautobot", "nautobot-plugin"]
include = [
    "LICENSE",
    "README.md",
]

[tool.poetry.plugins."nautobot.workers"]
"clear" = "nautobot_chatops.workers.clear:clear"
"nautobot" = "nautobot_chatops.workers.nautobot:nautobot"

[tool.poetry.dependencies]
python = "^3.6"
nautobot = "*"
nautobot-capacity-metrics = "*"
texttable = "^1.6.2"
PyJWT = "^2.1.0"
webexteamssdk = "^1.3"
slack-sdk = "^3.4.2"
cryptography = "^3.4.7"

[tool.poetry.dev-dependencies]
black = "*"
yamllint = "*"
bandit = "*"
pylint = "*"
pylint-django = "*"
pydocstyle = "*"
prybar = "*"
invoke = "*"
flake8 = "*"

[tool.black]
line-length = 120
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | settings.py     # This is where you define files that should not be stylized by black
                     # the root of the project
)
'''
[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.masonry.api"

