[tool.poetry]
name = "jq_test"
version = "0.2.0"
description = ""
authors = ["fikirsiz <hromus@gmail.com>"]
packages = [
    { include = "jq_test" },
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
