# -*- coding: utf-8 -*-

# SPDX-FileCopyrightText: 2016-2019 The Atlite Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: atlite
channels:
  - defaults
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - scipy
  - pandas>=1.0
  - xarray>=0.16.2
  - netcdf4
  - dask>=0.18.0,<20.04.0
  - yaml
  - geopandas
  - cdsapi
  - pyproj>=2.0
  - rasterio>=1.0

  # Recommended for pandas and xarray
  - bottleneck
  - numexpr

  # For travis and testing
  - pip
  - pytest

