# adapted from https://github.com/marketplace/actions/flake8-action
name: PEP8

on: [pull_request, push]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.10
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 --ignore E999,N802,N806,W503,W504 --exclude=setup.py,tests,__init__.py,ooipy/__init__.py,ooipy/request/__init__.py,ooipy/hydrophone/__init__.py,,ooipy/ctd/__init__.py,ooipy/surface_buoy/__init__.py,ooipy/visualize/__init__.py,docs --tee --output-file=flake8_log.txt `find . -name *.py | grep -v ./setup.py | grep -v /doc/`
      - name: Upload flake8 resutls
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: flake8_artifact
          path: flake8_log.txt
