[tool.poetry]
name = "pyfactcast"
version = "0.0.1"
description = "A python client library for FactCast"
authors = ["Eduard Thamm <eduard.thamm@thammit.at>"]
license = "ASL2"

[tool.poetry.dependencies]
python = "^3.7"
grpcio = "^1.37.1"


[tool.poetry.dev-dependencies]
Sphinx = "<4"
black = "^21.5b1"
flake8 = "^3.9.2"
pytest = "^6.2.4"
mypy = "^0.812"
rstcheck = "^3.3.1"
sphinx-autobuild = "^2021.3.14"
pytest-cov = "^2.11.1"
pytest-randomly = "^3.8.0"
pre-commit = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.coverage.run]
omit = ["pyfactcast/grpc/generated/*", "*__init__.py"]

[tool.pytest.ini_options]
addopts = "-rsxX -l --tb=short --strict-markers --cov-report term --cov=pyfactcast --cov-fail-under=85 --cov-branch"
xfail_strict = true
testpaths = [
    "tests",
]
filterwarnings = "ignore:.*the imp module is deprecated.*:DeprecationWarning"
markers = [
  "integration: marks tests that use mock and are therefore slower.",
  "usecase: marks tests that represent business logic."
]

[tool.black]
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | pyfactcast/grpc/generated
)
'''
