
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-14T07:05:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ecf045cf65824f55868e18e6fba45301038d6356",
 "version": "0.7.0.post.dev128"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
