[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ["py36", "py37", "py38"]
exclude = '''

(
  /(
      \.eggs
    | \.git
    | \.egg-info
    | \.tox
    | \.venv
    | build
    | doc
    | sphinx
    | dist
  )/
  | setup.py

)
'''
