# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ModernRelay CI

on:
  push:
    branches: [ master ]
    paths:
      - "ModernRelay/**"
      - "setup.py"
  pull_request:
    branches: [ master ]
    paths:
      - "ModernRelay/**"
      - "setup.py"

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-18.04", "ubuntu-20.04", "windows-latest" ]
        python-version: [ "3.6", "3.7", "3.8", "3.9", "pypy3" ]
        
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
    - name: "Checkout latest commit"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Set up Python ${{ matrix.python-version }}"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -e .[dev]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov --cov-report=xml --cov-report=term
