[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4"
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/dask_histogram/version.py"

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["tests"]
