[tool.poetry]
name = "pyhustler"
version = "0.5.0"
description = ""
authors = ["ashdaily <ashtokyo31@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
