
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-11T20:00:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9926e07c26f79e47727b5505d189f8e66ae53405",
 "version": "2.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
