import logging

KHL_API_BASEURL = "https://www.kaiheila.cn/api"

KHL_API_GATEWAY = "/v3/gateway/index"
KHL_API_CREATE_MSG = "/v3/message/create"

LOGGING_FILE_LEVEL = logging.INFO
LOGGING_CONSOLE_LEVEL = logging.INFO

# configurable items for bot
MAX_PROCESSING_NUMBER = "MAX_PROCESSING_NUMBER"
MAX_CONSUMER_NUMBER = "MAX_CONSUME_NUMBER"
MAX_EVENT_QUEUE_SIZE = "MAX_EVENT_QUEUE_SIZE"
PROCESSING_IDLE_TIMEOUT = "PROCESSING_IDLE_TIMEOUT"

# keys for bot
BOT_MESSAGE_TYPE_INTERVAL = 0
BOT_MESSAGE_TYPE_COMMAND = 1

BOT_KEY_MESSAGE_TYPE = "type"
BOT_KEY_MESSAGE_DATA = "data"

# keys for commander
COMMANDER_KEY_PARAM_NUMBER = "param_number"
COMMANDER_KEY_HANDLE = "handle"
COMMANDER_KEY_PARTIAL = "partial"
COMMANDER_KEY_PERIOD = "period"
COMMANDER_KEY_TIMES = "times"

# khl message type
KHL_MSG_TEXT = 1
KHL_MSG_CARD = 10
KHL_MSG_MARKDOWN = 9
