[tool.poetry]
name = "app-typer"
version = "0.1.0"
description = ""
authors = ["ysd <helloysd@foxmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
typer = {extras = ["all"], version = "^0.3.2"}

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
app-typer = "app_typer.main:app"
