[tool.poetry]
name = "fuzzy-c-means"
version = "1.4.0"
description = ""
authors = ["Madson Dias <madsonddias@gmail.com>", "dirk <https://github.com/dirknbr>", "José Alberth <jalberth14@gmail.com>"]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/omadson/fuzzy-c-means"
repository = "https://github.com/omadson/fuzzy-c-means"
keywords = ["machine-learning", "data-science", "fuzzy-c-means", "clustering"]
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

packages = [
    { include = "fcmeans" }
]


[tool.poetry.dependencies]
python = "^3.8"
jax = "^0.2.7"
jaxlib = "^0.1.65"
numpy = {version = "^1.20.2", optional = true}
jupyterlab = {version = "^3.0.14", optional = true}
scikit-learn = {version = "^0.24.2", optional = true}
Pillow = {version = "^8.2.0", optional = true}
matplotlib = {version = "^3.4.1", optional = true}
typer = {version = "^0.3.2", optional = true}
tabulate = {version = "^0.8.9", optional = true}

[tool.poetry.extras]
windows = ["numpy"]
examples = ["jupyterlab", "scikit-learn", "Pillow", "matplotlib", "numpy"]
cli = ["typer", "tabulate", "numpy"]


[tool.poetry.dev-dependencies]
commitizen = "^2.17.6"
pre-commit = "^2.12.1"
typer-cli = "^0.0.11"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = false

[tool.poetry.scripts]
fcm = 'fcmeans.cli:app'
