name: unittests

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - master
      - develop
      - "release/*"
      - "hotfix/*"
  pull_request:

jobs:
  tests_graph:
    runs-on: ubuntu-latest
    timeout-minutes: 150
    strategy:
      max-parallel: 4
      fail-fast: False
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]
    name: JIT compiled tests for Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Set up Python ${{ matrix.python-version }}

        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-feature=2020-resolver --use-feature=in-tree-build .[alldev]
      - name: Test with pytest
        run: |
          coverage run --source=. --omit=".tox/*,*/test*,*/minimizers/interface.py,*/core/testing.py" --branch -m pytest .
          coverage report

          bash utils/ci/test_examples.sh
          bash utils/ci/test_tutorials.sh

          bash utils/ci/testbuild_docs.sh

  tests_eager:
    runs-on: ubuntu-latest
    timeout-minutes: 150
    strategy:
      max-parallel: 4
      fail-fast: False
      matrix:
        python-version: [ 3.7, 3.8 ]
    name: Eager mode tests for Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Set up Python ${{ matrix.python-version }}

        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-feature=2020-resolver --use-feature=in-tree-build .[alldev]
      - name: Test with pytest
        run: |
          ZFIT_DO_JIT=0
          coverage run --source=. --omit=".tox/*,*/test*,*/minimizers/interface.py,*/core/testing.py" --branch -m pytest .
          coverage report

          bash utils/ci/test_examples.sh
          bash utils/ci/test_tutorials.sh
