[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "jjowl"
author = "JJoao"
author-email = "jj@di.uminho.pt"
home-page = "https://natura.di.uminho.pt/jjowl"
classifiers = ["License :: OSI Approved :: MIT License"]

requires = ["rdflib", "jjcli","owlrl", "unidecode"]

description-file = "jjowl.md"

[tool.flit.scripts]

owlcat  = "jjowl:mconcat"
owlgrep = "jjowl:mgrep"
owlexpandoo ="jjowl:mexpandpp"
owlclass  = "jjowl:mclass"
owllabel2term  = "jjowl:mlabel2term"
owln32owl = "jjowl:mn32owl"
owlxdxf = "jjowl:mxdxf"


