[tool.poetry]
name = "jrpygcloudml"
version = "0.1.1"
description = "Jumping Rivers: Google Cloud Machine Learning"
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = ">=3.6"
numpy = ">=1.19"

[tool.poetry.dev-dependencies]
