[tool.poetry]
name = "epic-py"
version = "0.1.0"
description = "ePIC API in Python"
authors = ["Triet Doan <triet.doan@gwdg.de>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://gitlab.gwdg.de/epic/epic-python-library"
keywords = ["pid", "handle", "persistent-identifier", "epic"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "~2.25.1"
pydantic = "~1.8.1"

[tool.poetry.dev-dependencies]
pytest = "~6.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
