[tool.poetry]
name = "materia"
version = "10.0.0"
description = "Module for integrated materials simulations."
authors = ["Ki-Jana Carter <kijana@mit.edu>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/kijanac/luz"
homepage = "https://github.com/kijanac/luz"

[tool.poetry.dependencies]
python = "^3.9"
cclib = "^1.6.4"
dlib = "^19.21.1"
networkx = "^2.5"
numpy = "^1.19.4"
PubChemPy = "^1.0.4"
scipy = "^1.5.4"
spglib = "^1.16.0"
dask = "^2020.12.0"
dask-jobqueue = "^0.7.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
poetry2conda = "^0.3.0"
"ruamel.yaml" = "^0.16.12"
toml = "^0.10.2"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"

[tool.poetry2conda]
name = "materia"

[tool.poetry2conda.dependencies.rdkit]
name = "rdkit"
channel = "conda-forge"
version = "^2020.09.4"

[tool.poetry2conda.dependencies.openbabel]
name = "openbabel"
channel = "conda-forge"
version = "^v3.1.1"

[tool.manage.conda-dependencies.rdkit]
git = "https://github.com/rdkit/rdkit.git"

[tool.manage.conda-dependencies.openbabel]
git = "https://github.com/openbabel/openbabel.git"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
