[tool.poetry]
authors = ["m09 <142691+m09@users.noreply.github.com>"]
classifiers = ["Topic :: Software Development :: Build Tools"]
description = "Tool to handle multiple beamer decks."
homepage = "https://github.com/m09/deckz"
license = "Apache-2.0"
name = "deckz"
readme = "README.md"
version = "13.4.0"

[tool.poetry.dependencies]
Jinja2 = "^2.11.3"
PyYAML = "^5.4.1"
appdirs = "^1.4.4"
attrs = "^20.3.0"
google-api-python-client = "^2.2.0"
google-auth-oauthlib = "^0.4.4"
python = "^3.8"
rich = "^10.1.0"
sendgrid = "^6.7.0"
typer = {version = "^0.3.2", extras = ["all"]}
watchdog = "^2.0.2"
pygit2 = "^1.5.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.1"
flake8-bugbear = "^21.4.3"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.1"
mypy = "^0.812"
"pdfminer.six" = "^20201018"
pylint = "^2.7.4"
pytest = "^6.2.3"
pytest-cov = "^2.11.1"

[tool.poetry.scripts]
deckz = 'deckz.cli:main'

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
