# Generated by Django 3.2 on 2021-04-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerboard', '0003_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
