[tool.poetry]
name = "ModularAPI"
version = "0.5.0"
description = "A CLI Framework based on FastAPI and Typer using module-based architecture."
authors = ["Modular-lab <contact.flapili@gmail.com>"]
license = "MIT"
homepage = "https://modular-lab.github.io/Modular-API/"
repository = "https://github.com/Modular-Lab/Modular-API"
include = ["LICENSE"]

[tool.poetry.dependencies]
python = "^3.6.1"
GitPython = "^3.1.13"
alembic = "^1.5.5"
psycopg2-binary = "^2.8.6"
typer = {extras = ["all"], version = "^0.3.2"}
pydantic = {extras = ["email", "dotenv"], version = "^1.8.1"}
gino = "^1.0.1"
gino-starlette = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
ModularAPI = "modularapi.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
