[tool.poetry]
name = "jrpymc3"
version = "0.1.1"
description = "Jumping Rivers: Bayesian Inference with PyMC3"
authors = ["Jamie <jamie@jumpingrivers.com>", "Jack <jack@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
