[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ausmints_calculator"
author = "Janis Ausmints Vitols"
description-file = "README.md"
author-email = "Ausmints@gmail.com"
home-page = "https://github.com/TuringCollegeSubmissions/jausmi-DT.1.1"
classifiers = [ "License :: OSI Approved :: MIT License",]

