[project]
name = "flask-sn-generator"
version = "0.1.2"
description = "generate global unique increased serial number"
readme = "README.rst"
authors = ["juforg <juforg@gmail.com>"]
requires-python = ">=3.7"
repository = "https://github.com/juforg/flask-sn-generator"
license = {file = "LICENSE"}
classifiers = [
    'Environment :: Plugins',
    'Framework :: Flask',
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    'Natural Language :: English',
    'Natural Language :: Chinese (Simplified)',
    "Programming Language :: Python",
    'Programming Language :: Python :: 3',
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
]

[project.dependencies]
python = "^3.7"
tomlkit = ">=0.5.3,<0.8.0"
cleo = ">=0.7.2,<0.9.0"
licensename = "^0.4.2"
requests = "^2.21"

[project.dev-dependencies]
pytest = "^6.2"
pre-commit = "^2.12"
towncrier = "^21.3"
pytest-cov = "^2.11"
responses = "^0.13.2"

[build-system]
requires = [
    "wheel",
    "setuptools"
    ]
