[build-system]
requires = [
    "setuptools", 
    "wheel",
    "cycler==0.10.0",
    "decorator==5.0.7",
    "elementpath==1.3.3",
    "ephem==3.7.7.1",
    "kiwisolver==1.3.1",
    "matplotlib==3.4.2",
    "networkx==2.2",
    "numpy==1.20.3",
    "opencv-python==4.2.0.32",
    "Pillow==8.2.0",
    "psutil==5.8.0",
    "py-trees==0.8.3",
    "pydot==1.4.2",
    "pyparsing==2.4.7",
    "python-dateutil==2.8.1",
    "Shapely==1.7.1",
    "simple-watchdog-timer==0.1.1",
    "six==1.16.0",
    "tabulate==0.8.9",
    "xmlschema==1.0.18"
]

build-backend = "setuptools.build_meta"
