
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-13T11:48:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d79cf26e7fb5ce3fcb34060771ea4992e19dc46a",
 "version": "2.6.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
