name: CI

on: [push, pull_request]

env:
  MPLBACKEND: Agg
  PYTEST_ADDOPTS: --color=yes

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # make sure we have version info
      - run: git fetch --tags

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python --version
          pip install -U pip setuptools wheel
          pip install --use-feature=2020-resolver -e .[all]
          pip freeze

      - name: Tests without external data
        run: |
          pytest -m "not needs_data" --cov=pyirf --cov-report=xml

      - uses: codecov/codecov-action@v1

      - name: Tests with external data
        env:
          DATA_PASSWORD: ${{ secrets.DATA_PASSWORD }}
        run: |
          ./download_test_data.sh
          pytest -m "needs_data"

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --tags

      - name: Download data
        env:
          DATA_PASSWORD: ${{ secrets.DATA_PASSWORD }}
        run: |
          ./download_test_data.sh

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: |
            apt update --yes && apt install --yes git build-essential pandoc curl
            pip install -U pip setuptools wheel sphinx
            pip install -e '.[docs]'
            python examples/calculate_eventdisplay_irfs.py
          build-command: make html SPHINXOPTS="-W --keep-going -n --color -w /tmp/sphinx-log"

      - name: Deploy to gihub pages
        # only run on push to master
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_build/html
          CLEAN: true
          SINGLE_COMMIT: true
