[tool.poetry]
name = "persist"
version = "3.1"
description = "Persistent archival of python objects in an importable format."
authors = ["Michael McNeil Forbes <michael.forbes+python@gmail.com>"]
license = "LGPL-2.1-or-later"
readme = "README.rst"
repository = "https://alum.mit.edu/www/mforbes/hg/forbes-group/persist"
documentation = "http://persist.readthedocs.org"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]


[tool.poetry.dependencies]
python = "^3.6.2"
"zope.interface" = "^5.4.0"
importlib-metadata = {version = "^4.0.1", python="<3.8"}
six = "^1.15.0"

# Optional dependencies for testing, building the docs, etc.

# These have issues with python 3.6... so don't restrict and let pip deal with it.
scipy = [
    {version = "^1.5.4", python="<3.7", optional = true},
    {version = "^1.6.3", python=">=3.7,<3.10", optional = true}]

h5py = [
    {version = "*", python="<3.7", optional = true},
    {version = "^3.2.1", python="^3.7", optional = true}]
pytest = {version = "^6.2.4", optional = true}
pytest-cov = {version = "^2.11.1", optional = true}

Sphinx = {version = "^3.5.4", optional = true}
sphinx-rtd-theme = {version = "^0.5.2", optional = true}
sphinxcontrib-zopeext = {version = "^0.2.4", optional = true}
nbsphinx = {version = "^0.8.4", optional = true}
mmf-setup = {version = "^0.4.0", optional = true}
ipython = [
#    {version = "*", python="<3.7", optional = true},
    {version = "^7.23.1", python=">=3.7", optional = true}
]

[tool.poetry.extras]
test = [
    "pytest",
    "pytest-cov",
    "pytest-flake8",
    "pytest-xdist",
    "scipy",   # Will bring in numpy
    "h5py"
]

doc = [
    "Sphinx",
    "sphinx_rtd_theme",
    "sphinxcontrib.zopeext",
    "ipython",
    "nbsphinx",
    "mmf-setup",
    "pycallgraph",
]

[tool.poetry.urls]
"Issues" = "https://alum.mit.edu/www/mforbes/hg/forbes-group/persist/issues"
"Git Mirror" = "https://github.com/forbes-group/persist"

[tool.poetry.dev-dependencies]
pip = "^21.1.0"
black = "^21.5b1"

# mercurial = "^5.7.1"
# hg-git = "^0.10.0"
# hg-evolve = "^10.3.1"
# hg-evolve = "^10.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

######################################################################
# PyTest
[tool.pytest.ini_options]
testpaths = [ "tests", "src/persist" ]
markers = [
    # mark test as a benchmark.  (Might be slow, or platform dependent)
    "bench",
    # mark test as slow.
    "slow",
]
addopts = [
    "-m not bench",
    "--doctest-modules",
    "--cov",
    "--cov-report=html",
    "--cov-fail-under=96",
    "--no-cov-on-fail",
    #"-x",
    #"--pdb",
    #"--flake8",  # Disable until https://github.com/tholo/pytest-flake8/issues/8
]

doctest_optionflags = [
    "ELLIPSIS",
    "NORMALIZE_WHITESPACE",
    "IGNORE_EXCEPTION_DETAIL",
]

######################################################################
# Black
[tool.black]
exclude = '''
    /(
        \.git
      | \.hg
      | \.nox
      | \.venv
      | _build
      | build
      | dist
    )/
'''



# poetry add zope.interface importlib-metadata
# poetry add --optional Sphinx pytest pytest-cov sphinx-rtd-theme sphinxcontrib-zopeext nbsphinx h5py mmf-setup scipy
