[tool.poetry]
name = "repl_python3_discord-utilities-ChadFreeman"
version = "0.1.0"
description = ""
authors = ["ChadFreeman <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
twine = "^3.4.1"
wheel = "^0.36.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
