[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "calc_SB"
author = "Simas B"
author-email = "test@test.test"
home-page = "https://github.com/cyber-zen/GTx-CS1301"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"

