# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# vim: set nospell:
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
      - id: reorder-python-imports
        exclude: docs\/.*
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.4"
    hooks:
      - id: flake8
        additional_dependencies: [flake8-comprehensions, flake8-bugbear]
        exclude: docs\/.*
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.790"
    hooks:
      - id: mypy
