[tool.poetry]
name = "doar-utils"
version = "0.1.0-alpha1"
description = ""
authors = ["Yehuda Deutsch <yeh@uda.co.il>"]

packages = [
    { include = "doar" },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
