---
logging:
  log_level: DEBUG
  log_file_name: ModernRelay.log
  log_file_dir: .

tls:
  required: yes
  public_key: certs/cert.pem
  private_key: certs/key.pem

networking:
  port: 8025
  host_name: 172.16.128.109

files:
  spool_dir: spool/

peers:
  172.16.128.109/32:
    agent: GraphDeliveryAgent
    destinations: all
    authenticated: no

  172.16.128.119/32:
    agent: GraphDeliveryAgent
    destinations:
      - google.com
      - example.com
    authenticated: no