
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-12T10:09:21-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "787b3d7f80ed55cee636a301b668c0b2b0d42365",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
