[tool.poetry]
name        = "loggerithm"
version     = "1.1.1"
description = "Logging module for the Python programming language"
authors     = ["Totobird"]
license     = "MIT"
readme      = "README.md"
repository  = "https://github.com/toto-bird/python-loggerithm/"

[tool.poetry.dependencies]
python = "^3.9"
coloured = "^0.1"
toml = "^0.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
