[build-system]
requires = ["jupyter_packaging~=0.10,<2", "jupyterlab~=3.0", "wheel"]
build-backend = "jupyter_packaging.build_api"

[tool.jupyter-packaging.options]
skip-if-exists = ["jlab_aiidatree/labextension/static/style.js"]
ensured-targets = ["jlab_aiidatree/labextension/static/style.js", "jlab_aiidatree/labextension/package.json"]

[tool.jupyter-packaging.builder]
factory = "jupyter_packaging.npm_builder"

[tool.jupyter-packaging.build-args]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.check-manifest]
ignore = ["jlab_aiidatree/labextension/**", "yarn.lock", ".*", "package-lock.json"]

[tool.isort]
profile = "black"
