
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-10T10:10:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d161f937b75ec34f1a230669d6f8a2037a25d14c",
 "version": "0.4.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
