[tool.poetry]
name = "impm"
version = "0.1.0"
description = "Python utilities for improving interoperability between Minecraft data packs."
authors = ["Arcensoth <arcensoth@gmail.com>"]
license = "MIT"
readme = 'README.md'
repository = "https://github.com/Arcensoth/impm"
homepage = "https://github.com/Arcensoth/impm"
keywords = ["minecraft", "commands", "library", "utility", "datapack", "data"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
colorlog = "^4.2.1"

[tool.poetry.dev-dependencies]
black = "^21.5b0"
isort = "^5.8.0"
rope = "^0.19.0"

[tool.isort]
profile = "black"

[tool.pyright]
typeCheckingMode = "strict"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
