from dagster.core.execution.context.init import InitResourceContext as InitResourceContext
from dagster_utils.contrib.google import default_google_access_token as default_google_access_token
from data_repo_client import RepositoryApi
from typing import Any

def jade_data_repo_client(init_context: InitResourceContext) -> RepositoryApi: ...

class NoopDataRepoClient:
    class NoopResult:
        total: int
        def __init__(self, total: Any) -> None: ...
    class FakeJobResponse:
        completed: bool
        def __init__(self, completed: Any) -> None: ...
    def enumerate_datasets(self) -> NoopResult: ...
    def retrieve_job(self, job_id: str) -> FakeJobResponse: ...

def noop_data_repo_client(init_context: InitResourceContext) -> NoopDataRepoClient: ...
