from .repo_paths import (
    DIRECTORY_WITH_DATA,
    DIRECTORY_WITH_GRAPHS_IMAGES,
    DIRECTORY_WITH_SAVED_MODELS,
    ORIGINAL_RUSSIAN_DF_NAME,
    CLEANED_RUSSIAN_DF_NAME,
    ORIGINAL_ENGLISH_DF_NAME,
    TRANSLATED_CLEANED_ENGLISH_DF_NAME
)

from .aliases import (
    PAD_WORD,
    ORIGINAL_ENGLISH_TEXTS_COLUMN,
    TRANSLATED_CLEANED_TEXTS_COLUMN,
    ENGLISH_TEXTS_TOXIC_LABEL_COLUMN,
)

from .default_hyperparameters import (
    SEED,
    VALIDATION_SPLIT_PARTITION,
    DEFAULT_EPOCHS,
    DEFAULT_BATCH_SIZE,
)

from .graphs_style_params import (
    IMAGE_DPI,
    FONT_FAMILY,
    TITLE_GRAPH_FONT_SIZE,
    TITLE_GRAPH_FONT_WEIGHT,
)