[tool.poetry]
name = "simpleicons"
version = "4.21"
description = "Use a wide-range of icons derived from the simple-icons/simple-icons repo in python."
authors = ["Sachin Raja <sachinraja2349@gmail.com>"]
license = "MIT"
include = ["simpleicons/icons/*", "simpleicons/all.py"]
readme = "README.md"
repository="https://github.com/xCloudzx/simpleicons"

[tool.poetry.scripts]
generate = "scripts.build_package:build"

[tool.poetry.dependencies]
python = "^3.8"
reportlab = "^3.5.67"
Pillow = "^8.2.0"
svglib = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
