[tool.poetry]
name = "dnacentercli"
version = "2.1.1"
description = ""
authors = ["Jose Bogarin Solano <jbogarin@altus.cr>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
dnacentersdk = "^2.2.2"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
yapf = "^0.31.0"
black = "^21.5b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
