[tool.poetry]
name = "views_stepshift"
version = "0.2.1"
description = "The code used to run modelling pipelines at ViEWS"
authors = [
   "Frederick Hoyles",
   "Remco Jansen",
   "peder2911 <pglandsverk@gmail.com>"
   ]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.4"
toolz = "^0.11.1"
scikit-learn = "^0.24.2"
joblib = "^1.0.1"
statsmodels = "^0.12.2"

[tool.poetry.dev-dependencies]
jedi = "^0.18.0"
pylint = "^2.8.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
