# Generated by Django 3.2.2 on 2021-05-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unchained_auth', '0003_auto_20210511_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
    ]
