# coding: utf-8

"""
    Cisco Firepower Management Center Open API Specification

    **Specifies the REST URLs and methods supported in the Cisco Firepower Management Center API. Refer to the version specific [REST API Quick Start Guide](https://www.cisco.com/c/en/us/support/security/defense-center/products-programming-reference-guides-list.html) for additional information.**  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tac@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fmc_client
from fmc_client.models.port_object_group_override_list_container import PortObjectGroupOverrideListContainer  # noqa: E501
from fmc_client.rest import ApiException


class TestPortObjectGroupOverrideListContainer(unittest.TestCase):
    """PortObjectGroupOverrideListContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPortObjectGroupOverrideListContainer(self):
        """Test PortObjectGroupOverrideListContainer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fmc_client.models.port_object_group_override_list_container.PortObjectGroupOverrideListContainer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
