# coding: utf-8

"""
    Cisco Firepower Management Center Open API Specification

    **Specifies the REST URLs and methods supported in the Cisco Firepower Management Center API. Refer to the version specific [REST API Quick Start Guide](https://www.cisco.com/c/en/us/support/security/defense-center/products-programming-reference-guides-list.html) for additional information.**  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tac@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fmc_client
from fmc_client.models.vrf_i_pv6_static_route_model import VrfIPv6StaticRouteModel  # noqa: E501
from fmc_client.rest import ApiException


class TestVrfIPv6StaticRouteModel(unittest.TestCase):
    """VrfIPv6StaticRouteModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVrfIPv6StaticRouteModel(self):
        """Test VrfIPv6StaticRouteModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fmc_client.models.vrf_i_pv6_static_route_model.VrfIPv6StaticRouteModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
